'\" t
.\"     Title: globus-connect-server-web-cleanup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/28/2015
.\"    Manual: Globus Connect Server
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-CONNECT\-SER" "8" "05/28/2015" "University of Chicago" "Globus Connect Server"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-connect-server-web-cleanup \- Clean up MyProxy OAuth server configuration
.SH "SYNOPSIS"
.sp
\fBglobus\-connect\-server\-web\-cleanup\fR [\-h|\-\-help]
.sp
\fBglobus\-connect\-server\-web\-cleanup\fR {\-c FILENAME|\-\-config\-file=FILENAME} {\-v|\-\-verbose} {\-r PATH|\-\-root=PATH}
.SH "DESCRIPTION"
.sp
The \fBglobus\-connect\-server\-web\-cleanup\fR command deletes MyProxy OAuth service configuration previously created by running globus\-connect\-server\-web\-setup\&. It deletes configuration files, stops, and disables the MyProxy server\&.
.sp
If the \fB\-r \fR\fB\fIPATH\fR\fR or \fB\-\-root=\fR\fB\fIPATH\fR\fR command\-line option is used, \fBglobus\-connect\-server\-web\-cleanup\fR will delete MyProxy OAuth configuration in a subdirectory rooted at \fIPATH\fR instead of /\&. This means, for example, that \fBglobus\-connect\-server\-web\-cleanup\fR deletes MyProxy OAuth configuration files in \fIPATH\fR/etc/apache2 or \fIPATH\fR/etc/httpd\&.
.SH "OPTIONS"
.sp
The following options are available:
.PP
\fB\-h, \-\-help\fR
.RS 4
Display help information
.RE
.PP
\fB\-c FILENAME, \-\-config\-file=FILENAME\fR
.RS 4
Use configuration file
\fIFILENAME\fR
instead of
/etc/globus\-connect\-server\&.conf
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Print more information about tasks
.RE
.PP
\fB\-r PATH, \-\-root=PATH\fR
.RS 4
Use
\fIPATH\fR
as the directory prefix for the configuration files that
\fBglobus\-connect\-server\-web\-cleanup\fR
deletes\&.
.RE
.SH "ENVIRONMENT"
.PP
\fBGLOBUS_USER\fR
.RS 4
Default Globus user name
.RE
.PP
\fBGLOBUS_PASSWORD\fR
.RS 4
Default Globus password
.RE
.SH "SEE ALSO"
.sp
\fBglobus\-connect\-server\-web\-setup\fR(8)
