'\" t
.\"     Title: globus-connect-server-io-cleanup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/28/2015
.\"    Manual: Globus Connect Server
.\"    Source: University of Chicago
.\"  Language: English
.\"
.TH "GLOBUS\-CONNECT\-SER" "8" "05/28/2015" "University of Chicago" "Globus Connect Server"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
globus-connect-server-io-cleanup \- Remove a GridFTP server configuration and remove it from a Globus endpoint
.SH "SYNOPSIS"
.sp
\fBglobus\-connect\-server\-io\-cleanup\fR [\-h|\-\-help]
.sp
\fBglobus\-connect\-server\-io\-cleanup\fR {\-c FILENAME|\-\-config\-file=FILENAME} {\-v|\-\-verbose} {\-r PATH|\-\-root=PATH} {\-d|\-\-delete\-endpoint}
.SH "DESCRIPTION"
.sp
The \fBglobus\-connect\-server\-io\-cleanup\fR command deletes GridFTP service configuration previously created by running \fBglobus\-connect\-server\-io\-setup\fR and removes it from a Globus endpoint\&. It deletes configuration files, stops, and disables the GridFTP server\&. It also removes the server from an endpoint, optionally deleting the endpoint\&.
.sp
If the \fB\-d\fR or \fB\-\-delete\-endpoint\fR command\-line option is used, \fBglobus\-connect\-server\-io\-cleanup\fR removes the endpoint named in the configuration file as well as cleaning up generated configuration files\&.
.sp
If the \fB\-r \fR\fB\fIPATH\fR\fR or \fB\-\-root=\fR\fB\fIPATH\fR\fR command\-line option is used, \fBglobus\-connect\-server\-io\-cleanup\fR will remove its GridFTP configuration and certificates from a subdirectory rooted at \fIPATH\fR instead of /\&. This means, for example, that \fBglobus\-connect\-server\-io\-cleanup\fR deletes GridFTP configuration files in \fIPATH\fR/etc/gridftp\&.d\&.
.SH "OPTIONS"
.sp
The following options are available: \fB\-h, \-\-help\fR:: Display help information \fB\-c FILENAME, \-\-config\-file=FILENAME\fR:: Use configuration file FILENAME instead of /etc/globus\-connect\-server\&.conf \fB\-v, \-\-verbose\fR:: Print more information about tasks \fB\-r PATH, \-\-root=PATH\fR:: Add \fIPATH\fR as the directory prefix for the configuration files that \fBglobus\-connect\-server\-io\-setup\fR modifies\&. \fB\-d, \-\-delete\-endpoint\fR:: Delete the Globus endpoint
.SH "ENVIRONMENT"
.PP
\fBGLOBUS_USER\fR
.RS 4
Default Globus user name
.RE
.PP
\fBGLOBUS_PASSWORD\fR
.RS 4
Default Globus password
.RE
.SH "SEE ALSO"
.sp
\fBglobus\-connect\-server\-io\-setup\fR(8)
